# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/karatsuba_1/karatsuba_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==karatsuba_1 || ORIG_REF_NAME==karatsuba_1} -quiet] -quiet

# IP: bd/karatsuba_1/ip/karatsuba_1_karatsuba_pipeline_ip_0_0/karatsuba_1_karatsuba_pipeline_ip_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==karatsuba_1_karatsuba_pipeline_ip_0_0 || ORIG_REF_NAME==karatsuba_1_karatsuba_pipeline_ip_0_0} -quiet] -quiet

# IP: bd/karatsuba_1/ip/karatsuba_1_axi_dma_0_0/karatsuba_1_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==karatsuba_1_axi_dma_0_0 || ORIG_REF_NAME==karatsuba_1_axi_dma_0_0} -quiet] -quiet

# IP: bd/karatsuba_1/ip/karatsuba_1_xbar_0/karatsuba_1_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==karatsuba_1_xbar_0 || ORIG_REF_NAME==karatsuba_1_xbar_0} -quiet] -quiet

# IP: bd/karatsuba_1/ip/karatsuba_1_axi_interconnect_0_0/karatsuba_1_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==karatsuba_1_axi_interconnect_0_0 || ORIG_REF_NAME==karatsuba_1_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/karatsuba_1/ip/karatsuba_1_xbar_1/karatsuba_1_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==karatsuba_1_xbar_1 || ORIG_REF_NAME==karatsuba_1_xbar_1} -quiet] -quiet

# IP: bd/karatsuba_1/ip/karatsuba_1_axi_interconnect_1_0/karatsuba_1_axi_interconnect_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==karatsuba_1_axi_interconnect_1_0 || ORIG_REF_NAME==karatsuba_1_axi_interconnect_1_0} -quiet] -quiet

# IP: bd/karatsuba_1/ip/karatsuba_1_zynq_ultra_ps_e_0_0/karatsuba_1_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==karatsuba_1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==karatsuba_1_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/karatsuba_1/ip/karatsuba_1_naive_ip_0_0/karatsuba_1_naive_ip_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==karatsuba_1_naive_ip_0_0 || ORIG_REF_NAME==karatsuba_1_naive_ip_0_0} -quiet] -quiet

# IP: bd/karatsuba_1/ip/karatsuba_1_rst_ps8_0_99M_0/karatsuba_1_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==karatsuba_1_rst_ps8_0_99M_0 || ORIG_REF_NAME==karatsuba_1_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/karatsuba_1/ip/karatsuba_1_karatsuba_mult_ip_0_0/karatsuba_1_karatsuba_mult_ip_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==karatsuba_1_karatsuba_mult_ip_0_0 || ORIG_REF_NAME==karatsuba_1_karatsuba_mult_ip_0_0} -quiet] -quiet

# IP: bd/karatsuba_1/ip/karatsuba_1_auto_ds_0/karatsuba_1_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==karatsuba_1_auto_ds_0 || ORIG_REF_NAME==karatsuba_1_auto_ds_0} -quiet] -quiet

# IP: bd/karatsuba_1/ip/karatsuba_1_auto_pc_0/karatsuba_1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==karatsuba_1_auto_pc_0 || ORIG_REF_NAME==karatsuba_1_auto_pc_0} -quiet] -quiet

# IP: bd/karatsuba_1/ip/karatsuba_1_auto_us_0/karatsuba_1_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==karatsuba_1_auto_us_0 || ORIG_REF_NAME==karatsuba_1_auto_us_0} -quiet] -quiet

# IP: bd/karatsuba_1/ip/karatsuba_1_auto_us_1/karatsuba_1_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==karatsuba_1_auto_us_1 || ORIG_REF_NAME==karatsuba_1_auto_us_1} -quiet] -quiet

# XDC: c:/Karatsuba/Karatsuba_Multiplication/Karatsuba_kria/Karatsuba_kria.gen/sources_1/bd/karatsuba_1/karatsuba_1_ooc.xdc
